name=Sonic
version=1.1.0
author=Axxel
maintainer=Axxel <Axxel.Inkordia@proton.me>
sentence=Control sencillo del HC-SR04
paragraph=Librería con creación de objetos y usos como attach, scream, average
category=Sensors
architectures=*
