name=Sonic
version=3.0.0
author=Axxel
maintainer=Axxel <Axxel.Inkordia@proton.me>
sentence=Simple HC-SR04 ultrasonic sensor and infrared sensorlibrary
paragraph=Supports multiple sensor objects with attach, scream/read and average methods. Returns -1 for invalid readings. Returns -2 for waiting.
category=Sensors
url=https://github.com/Axxel-otl/Sonic
architectures=*
license=GPL-3.0-or-later