name=Sonic
version=1.2.4
author=Axxel
maintainer=Axxel <Axxel.Inkordia@proton.me>
sentence=Simple HC-SR04 ultrasonic sensor library
paragraph=Supports multiple sensor objects with attach, scream and average methods. Returns -1 for invalid readings.
category=Sensors
url=https://github.com/Axxel-otl/Sonic
architectures=*
